name: Send email every 5 minutes

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send email
      uses: sendgrid/email-action@v1
      with:
        api-key: ${{ secrets.SENDGRID_API_KEY }}
        to: steven.suing@gmail.com
        from: steven.suing@gmail.com
        subject: "Take a break and stretch!"